packages:
  - "apps/*"
  - "packages/*"
  - "packages/providers/*"
  - "integration-tests"
allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  unrs-resolver: true
