import { model } from '@medusajs/framework/utils';

/**
 * wrdo_users — channel-agnostic primary user record.
 *
 * One row per human. Channel-specific identifiers (WhatsApp wa_id, Telegram
 * numeric id, Messenger PSID, web session subject) live in
 * `user_channel_identity` and point back to this row via `user_id`.
 *
 * Ported from product-tribe (wrdo-user module). In mercur this is a CLEAN
 * install — no legacy `tribe_users`, so no dual-write scaffolding. The Medusa
 * migration is generated by `medusa db:generate wrdo_user` and committed
 * alongside this model (predeploy fails on a model without a migration).
 *
 * POPIA: erasure flips `is_active = false` and cascades through
 * user_channel_identity. Hard delete is reserved for cross-platform erasure.
 */
const WrdoUser = model.define('wrdo_users', {
  id: model.id().primaryKey(),
  display_name: model.text().nullable(),
  marketing_consent: model.boolean().default(false),
  service_consent: model.boolean().default(true),
  is_active: model.boolean().default(true),
  registration_state: model.text().default('pending'),
  metadata: model.json().nullable(),
});

export default WrdoUser;
