import { MedusaService } from '@medusajs/framework/utils';

import UserChannelIdentity from './models/user-channel-identity';
import WrdoUser from './models/wrdo-user';

/**
 * WrdoUserModuleService — Medusa ORM layer for wrdo_users + user_channel_identity.
 *
 * Pure persistence: CRUD generated by MedusaService() (createWrdoUsers,
 * retrieveWrdoUser, listWrdoUsers, updateWrdoUsers, createUserChannelIdentities,
 * listUserChannelIdentities, …). The channel-identity resolution logic lives in
 * WrdoUserService (wrdo-user.service.ts), which wraps this class.
 */
class WrdoUserModuleService extends MedusaService({
  WrdoUser,
  UserChannelIdentity,
}) {}

export default WrdoUserModuleService;
